POST http://localhost:8000
Content-Type: application/json

{"position": "second_hand", "round": 10, "crystal": 9, "player_hand_cards": ["DMF_002", "GDB_310", "TOY_000", "GDB_310", "GDB_435"], "player_deck_cards": [], "played_actions": [["MIS_307"], ["CS3_007", "TOY_508"], ["MIS_307", "TOY_000"], ["GDB_901", "CS3_007"], ["DEEP_008"], ["GDB_320", "TOY_508"], [], ["GDB_445", "GDB_451"], []], "rival_battle_cards": ["VAC_702", "ONY_001t", "ONY_001t", "ONY_001t", "ONY_001t"], "companion_battle_cards": ["CS3_007", "GDB_310"], "companion_burst_cards": []}

# {"position": "second_hand", "round": 11, "crystal": 10, "player_hand_cards": ["VAC_323t", "GDB_320", "GDB_445", "GDB_320", "TOY_508", "VAC_321", "GDB_445", "VAC_323", "GDB_451", "GDB_434"], "player_deck_cards": [], "played_actions": [[], ["GDB_435"], ["GDB_901"], ["GDB_434"], ["GDB_310", "VAC_323"], ["MIS_307", "VAC_328", "CS3_007", "TOY_508"], ["GDB_435", "GDB_901", "GAME_005", "GDB_451"], ["MIS_307t1"], ["MIS_307", "MIS_307t1"], []], "rival_battle_cards": ["BAR_916", "TTN_960t6", "TTN_960t6"], "companion_battle_cards": ["VAC_321", "GDB_434", "GDB_310", "CS3_007"], "companion_burst_cards": []}