POST http://localhost:8000
Content-Type: application/json

{
    "position": "landlord",
    "crystal": 5,
    "player_hand_cards": [
        "GAME_005", 
        "CS3_034", 
        "GDB_434", 
        "GDB_310"
    ],
    "player_deck_cards": [
    ],
    "played_actions": [["VAC_328", "TOY_000"]],
    "rival_battle_cards": [],
    "companion_battle_cards": []
}